services:
  postgres:
    image: postgres:16
    container_name: notification-platform-postgres
    environment:
      POSTGRES_DB: notification_platform
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: notification
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:4-management
    container_name: notification-platform-rabbitmq
    command: sh -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
    environment:
      RABBITMQ_DEFAULT_USER: notification
      RABBITMQ_DEFAULT_PASS: notification
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    container_name: notification-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:7-alpine
    container_name: notification-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  jaeger:
    image: jaegertracing/all-in-one
    container_name: notification-platform-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    container_name: notification-platform-otel-collector
    command:
      - "--config=/etc/otelcol-contrib/config.yml"
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./observability/otel-collector/config.yml:/etc/otelcol-contrib/config.yml:ro
    depends_on:
      - jaeger

  prometheus:
    image: prom/prometheus
    container_name: notification-platform-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rabbitmq

  grafana:
    image: grafana/grafana
    container_name: notification-platform-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  postgres-data:
  rabbitmq-data:
  redis-data:
  grafana-data:
