spring:
  application:
    name: notification-projection-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: ${PROJECTION_MAX_POLL_RECORDS:500}
    listener:
      ack-mode: record
      concurrency: ${PROJECTION_KAFKA_CONCURRENCY:3}
management:
  endpoint:
    health:
      group:
        readiness:
          include: readinessState,db
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
