package com.notificationplatform.webhookworker;
import com.fasterxml.jackson.databind.ObjectMapper;import com.notificationplatform.contracts.DeliveryRequested;import com.notificationplatform.workersupport.KafkaWorkerCoordinator;
import io.micrometer.core.instrument.MeterRegistry;import java.util.UUID;import org.apache.kafka.clients.consumer.ConsumerRecord;import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.kafka.core.KafkaTemplate;import org.springframework.kafka.support.Acknowledgment;import org.springframework.stereotype.Component;
@Component class WebhookKafkaDeliveryConsumer{
 private final ObjectMapper mapper;private final JdbcTemplate jdbc;private final WebhookWorkerServiceApplication.WebhookDeliveryProcessor processor;private final KafkaWorkerCoordinator coordinator;
 WebhookKafkaDeliveryConsumer(ObjectMapper mapper,JdbcTemplate jdbc,WebhookWorkerServiceApplication.WebhookDeliveryProcessor processor,KafkaTemplate<Object,Object> kafka,MeterRegistry meters,
  @Value("${worker.provider.max-concurrency:32}")int concurrency,@Value("${worker.provider.rate-per-second:100}")int rate){this.mapper=mapper;this.jdbc=jdbc;this.processor=processor;coordinator=new KafkaWorkerCoordinator("WEBHOOK",kafka,meters,concurrency,rate);}
 @KafkaListener(topics={"notification.webhook.v1","notification.webhook.retry-1m.v1","notification.webhook.retry-5m.v1","notification.webhook.retry-30m.v1"},groupId="${notification.kafka.group:webhook-worker-v1}")
 void consume(ConsumerRecord<String,String> record,Acknowledgment ack){String json=record.value();DeliveryRequested d;try{d=mapper.readValue(json,DeliveryRequested.class);}catch(Exception e){coordinator.malformed(record,json,e,ack);return;}try{var job=new WebhookWorkerServiceApplication.DeliveryJob(UUID.fromString(d.eventId()),UUID.fromString(d.notificationId()),UUID.fromString(d.deliveryId()),d.recipientAddress(),d.subject(),d.body());coordinator.handle(d,record,ack,()->processor.process(job),()->lookup(job.eventId()));}catch(IllegalArgumentException e){coordinator.malformed(record,json,e,ack);}}
 private KafkaWorkerCoordinator.AttemptResult lookup(UUID e){return jdbc.query("SELECT provider_message_id,status,error_code,error_message FROM delivery_attempts WHERE event_id=? ORDER BY created_at DESC LIMIT 1",rs->rs.next()?new KafkaWorkerCoordinator.AttemptResult(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)):null,e);}
}
