global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert-rules.yml

scrape_configs:
  - job_name: notification-api-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-api-service:8081"]
  - job_name: template-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["template-service:8082"]
  - job_name: preference-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["preference-service:8083"]
  - job_name: notification-orchestrator-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-orchestrator-service:8091"]
  - job_name: notification-projection-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-projection-service:8092"]
  - job_name: outbox-publisher-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["outbox-publisher-service:8084"]
  - job_name: email-worker-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["email-worker-service:8085"]
  - job_name: sms-worker-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["sms-worker-service:8086"]
  - job_name: push-worker-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["push-worker-service:8087"]
  - job_name: admin-bff-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["admin-bff-service:8088"]
  - job_name: in-app-worker-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["in-app-worker-service:8089"]
  - job_name: webhook-worker-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["webhook-worker-service:8090"]
  - job_name: rabbitmq
    static_configs:
      - targets: ["rabbitmq:15692"]
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8888"]
