import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Gauge, Trend } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const PRODUCT_ID = __ENV.PRODUCT_ID;
const TEMPLATE_KEY = __ENV.TEMPLATE_KEY || "load-test-email";
const BATCH_SIZES = (__ENV.BATCH_SIZES || "100,1000,10000")
  .split(",")
  .map((value) => Number(value.trim()))
  .filter((value) => value > 0);

const batchCreationTime = new Trend("k6_batch_creation_time");
const batchNotificationsAccepted = new Counter("k6_batch_notifications_accepted");
const outboxPending = new Gauge("k6_outbox_pending_count");
const retryScheduled = new Gauge("k6_deliveries_retry_scheduled_count");

export const options = {
  scenarios: {
    batch_sizes: {
      executor: "shared-iterations",
      vus: 1,
      iterations: 1,
      maxDuration: __ENV.MAX_DURATION || "30m",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.05"],
    k6_batch_creation_time: ["p(95)<120000"],
    k6_batch_notifications_accepted: ["count>0"],
  },
};

export function setup() {
  if (PRODUCT_ID) {
    return { productId: PRODUCT_ID, templateKey: TEMPLATE_KEY };
  }

  return createProductAndTemplate("batch");
}

export default function (data) {
  for (const size of BATCH_SIZES) {
    const batchId = unique(`batch-${size}`);
    const payload = {
      productId: data.productId,
      idempotencyKey: `batch-${batchId}`,
      items: Array.from({ length: size }, (_, index) => batchItem(data, batchId, index)),
    };

    const response = postJson("/api/v1/notification-batches", payload, "180s");
    batchCreationTime.add(response.timings.duration);

    const ok = check(response, {
      [`batch ${size} accepted`]: (res) => res.status === 201,
      [`batch ${size} latency recorded`]: (res) => res.timings.duration > 0,
    });

    if (ok) {
      batchNotificationsAccepted.add(size);
    }

    captureBackendGauge("outbox_pending_count", outboxPending);
    captureBackendGauge("deliveries_retry_scheduled_count", retryScheduled);

    sleep(Number(__ENV.BATCH_PAUSE_SECONDS || 10));
  }
}

function createProductAndTemplate(label) {
  const suffix = unique(label);
  const product = postJson("/api/v1/admin/products", {
    name: `Load ${label} ${suffix}`,
  });

  check(product, { "product created": (res) => res.status === 201 });

  const productId = product.json("id");
  const templateKey = `${TEMPLATE_KEY}-${suffix}`;
  const template = postJson("/api/v1/admin/templates", {
    productId,
    templateKey,
    channel: "EMAIL",
    version: 1,
    subject: "Load test batch",
    content: "Hello {{name}}, this batch item was generated by k6.",
    status: "ACTIVE",
  });

  check(template, { "template created": (res) => res.status === 201 });
  return { productId, templateKey };
}

function batchItem(data, batchId, index) {
  const id = `${batchId}-${index}`;

  return {
    templateKey: data.templateKey,
    requestedChannels: ["EMAIL"],
    externalUserId: `batch-user-${id}`,
    idempotencyKey: `batch-item-${id}`,
    category: "LOAD_TEST",
    priority: index % 10 === 0 ? "HIGH" : "NORMAL",
    payload: {
      name: `Batch User ${index}`,
      runId: id,
    },
    recipient: {
      email: `batch-${id}@example.test`,
    },
  };
}

function captureBackendGauge(metricName, gauge) {
  const response = http.get(`${BASE_URL}/actuator/prometheus`, { timeout: "10s" });
  if (response.status !== 200) {
    return;
  }

  const value = extractPrometheusMetric(response.body, metricName);
  if (value !== null) {
    gauge.add(value);
  }
}

function extractPrometheusMetric(body, metricName) {
  const regex = new RegExp(`^${metricName}(?:\\{[^}]*\\})?\\s+([0-9.eE+-]+)$`, "m");
  const match = body.match(regex);
  return match ? Number(match[1]) : null;
}

function postJson(path, body, timeout = "30s") {
  return http.post(`${BASE_URL}${path}`, JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    timeout,
  });
}

function unique(prefix) {
  const vu = typeof __VU === "undefined" ? 0 : __VU;
  const iter = typeof __ITER === "undefined" ? 0 : __ITER;
  return `${prefix}-${Date.now()}-${vu}-${iter}-${Math.random().toString(36).slice(2, 10)}`;
}
