import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Rate } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const PRODUCT_ID = __ENV.PRODUCT_ID;
const TEMPLATE_KEY = __ENV.TEMPLATE_KEY || "load-test-email";

const notificationsCreated = new Counter("k6_notifications_created");
const notificationErrors = new Rate("k6_notification_errors");

export const options = {
  scenarios: {
    notification_throughput: {
      executor: "constant-vus",
      vus: Number(__ENV.VUS || 100),
      duration: __ENV.DURATION || "5m",
      gracefulStop: "30s",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.05"],
    http_req_duration: ["p(95)<1000", "p(99)<2000"],
    k6_notification_errors: ["rate<0.05"],
    k6_notifications_created: ["count>100"],
  },
};

export function setup() {
  if (PRODUCT_ID) {
    return { productId: PRODUCT_ID, templateKey: TEMPLATE_KEY };
  }

  return createProductAndTemplate("throughput");
}

export default function (data) {
  const response = postJson("/api/v1/notifications", notificationPayload(data, "throughput"));
  const ok = response.status === 201;

  notificationErrors.add(!ok);
  if (ok) {
    notificationsCreated.add(1);
  }

  check(response, {
    "notification created": (res) => res.status === 201,
    "latency below 1s": (res) => res.timings.duration < 1000,
  });

  sleep(Number(__ENV.SLEEP_SECONDS || 0.1));
}

function createProductAndTemplate(label) {
  const suffix = unique(label);
  const product = postJson("/api/v1/admin/products", {
    name: `Load ${label} ${suffix}`,
  });

  check(product, { "product created": (res) => res.status === 201 });

  const productId = product.json("id");
  const templateKey = `${TEMPLATE_KEY}-${suffix}`;
  const template = postJson("/api/v1/admin/templates", {
    productId,
    templateKey,
    channel: "EMAIL",
    version: 1,
    subject: "Load test notification",
    content: "Hello {{name}}, this notification was generated by k6.",
    status: "ACTIVE",
  });

  check(template, { "template created": (res) => res.status === 201 });
  return { productId, templateKey };
}

function notificationPayload(data, prefix) {
  const id = unique(prefix);

  return {
    productId: data.productId,
    templateKey: data.templateKey,
    requestedChannels: ["EMAIL"],
    externalUserId: `load-user-${id}`,
    idempotencyKey: `load-${id}`,
    category: "LOAD_TEST",
    priority: pickPriority(),
    payload: {
      name: "Load Tester",
      runId: id,
    },
    recipient: {
      email: `load-${id}@example.test`,
    },
  };
}

function pickPriority() {
  const value = Math.random();
  if (value < 0.15) {
    return "HIGH";
  }
  if (value < 0.85) {
    return "NORMAL";
  }
  return "LOW";
}

function postJson(path, body) {
  return http.post(`${BASE_URL}${path}`, JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    timeout: "30s",
  });
}

function unique(prefix) {
  const vu = typeof __VU === "undefined" ? 0 : __VU;
  const iter = typeof __ITER === "undefined" ? 0 : __ITER;
  return `${prefix}-${Date.now()}-${vu}-${iter}-${Math.random().toString(36).slice(2, 10)}`;
}
