import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Gauge, Rate } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const FAILURE_BASE_URL = __ENV.FAILURE_BASE_URL || BASE_URL;
const PRODUCT_ID = __ENV.PRODUCT_ID;
const FAILURE_PRODUCT_ID = __ENV.FAILURE_PRODUCT_ID || PRODUCT_ID;
const TEMPLATE_KEY = __ENV.TEMPLATE_KEY || "load-test-email";
const FAILURE_TEMPLATE_KEY = __ENV.FAILURE_TEMPLATE_KEY || TEMPLATE_KEY;

const notificationsCreated = new Counter("k6_provider_failure_notifications_created");
const notificationErrors = new Rate("k6_provider_failure_notification_errors");
const retryScheduled = new Gauge("k6_deliveries_retry_scheduled_count");
const deadLettered = new Gauge("k6_deliveries_dead_lettered_count");
const providerFailures = new Gauge("k6_email_provider_send_failure_total");

export const options = {
  scenarios: {
    success_half: {
      executor: "constant-vus",
      exec: "successTraffic",
      vus: Number(__ENV.SUCCESS_VUS || 25),
      duration: __ENV.DURATION || "5m",
      gracefulStop: "30s",
    },
    temporary_failure_half: {
      executor: "constant-vus",
      exec: "temporaryFailureTraffic",
      vus: Number(__ENV.FAILURE_VUS || 25),
      duration: __ENV.DURATION || "5m",
      gracefulStop: "30s",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.10"],
    http_req_duration: ["p(95)<1500", "p(99)<3000"],
    k6_provider_failure_notification_errors: ["rate<0.10"],
    k6_provider_failure_notifications_created: ["count>0"],
  },
};

export function setup() {
  const success = PRODUCT_ID
    ? { productId: PRODUCT_ID, templateKey: TEMPLATE_KEY }
    : createProductAndTemplate(BASE_URL, "provider-success");

  const failure = FAILURE_PRODUCT_ID
    ? { productId: FAILURE_PRODUCT_ID, templateKey: FAILURE_TEMPLATE_KEY }
    : createProductAndTemplate(FAILURE_BASE_URL, "provider-temporary-failure");

  return { success, failure };
}

export function successTraffic(data) {
  sendNotification(BASE_URL, data.success, "provider-success");
}

export function temporaryFailureTraffic(data) {
  sendNotification(FAILURE_BASE_URL, data.failure, "provider-temp-failure");
}

export default function (data) {
  sendNotification(BASE_URL, data.success, "provider-default");
}

function sendNotification(baseUrl, data, prefix) {
  const response = postJson(baseUrl, "/api/v1/notifications", notificationPayload(data, prefix));
  const ok = response.status === 201;

  notificationErrors.add(!ok);
  if (ok) {
    notificationsCreated.add(1);
  }

  check(response, {
    "notification accepted": (res) => res.status === 201,
  });

  if (__ITER % Number(__ENV.METRIC_SAMPLE_EVERY || 25) === 0) {
    captureBackendGauge(baseUrl, "deliveries_retry_scheduled_count", retryScheduled);
    captureBackendGauge(baseUrl, "deliveries_dead_lettered_count", deadLettered);
    captureBackendGauge(baseUrl, "email_provider_send_failure_total", providerFailures);
  }

  sleep(Number(__ENV.SLEEP_SECONDS || 0.2));
}

function createProductAndTemplate(baseUrl, label) {
  const suffix = unique(label);
  const product = postJson(baseUrl, "/api/v1/admin/products", {
    name: `Load ${label} ${suffix}`,
  });

  check(product, { [`${label} product created`]: (res) => res.status === 201 });

  const productId = product.json("id");
  const templateKey = `${TEMPLATE_KEY}-${suffix}`;
  const template = postJson(baseUrl, "/api/v1/admin/templates", {
    productId,
    templateKey,
    channel: "EMAIL",
    version: 1,
    subject: "Load test provider failure",
    content: "Hello {{name}}, this provider failure notification was generated by k6.",
    status: "ACTIVE",
  });

  check(template, { [`${label} template created`]: (res) => res.status === 201 });
  return { productId, templateKey };
}

function notificationPayload(data, prefix) {
  const id = unique(prefix);

  return {
    productId: data.productId,
    templateKey: data.templateKey,
    requestedChannels: ["EMAIL"],
    externalUserId: `${prefix}-user-${id}`,
    idempotencyKey: `${prefix}-${id}`,
    category: "LOAD_TEST",
    priority: "NORMAL",
    payload: {
      name: "Provider Failure Tester",
      runId: id,
    },
    recipient: {
      email: `${prefix}-${id}@example.test`,
    },
  };
}

function captureBackendGauge(baseUrl, metricName, gauge) {
  const response = http.get(`${baseUrl}/actuator/prometheus`, { timeout: "10s" });
  if (response.status !== 200) {
    return;
  }

  const regex = new RegExp(`^${metricName}(?:\\{[^}]*\\})?\\s+([0-9.eE+-]+)$`, "m");
  const match = response.body.match(regex);
  if (match) {
    gauge.add(Number(match[1]));
  }
}

function postJson(baseUrl, path, body) {
  return http.post(`${baseUrl}${path}`, JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    timeout: "30s",
  });
}

function unique(prefix) {
  const vu = typeof __VU === "undefined" ? 0 : __VU;
  const iter = typeof __ITER === "undefined" ? 0 : __ITER;
  return `${prefix}-${Date.now()}-${vu}-${iter}-${Math.random().toString(36).slice(2, 10)}`;
}
