import http from "k6/http";
import { check, sleep } from "k6";
import { Counter, Gauge, Rate } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const PRODUCT_ID = __ENV.PRODUCT_ID;
const TEMPLATE_KEY = __ENV.TEMPLATE_KEY || "load-test-email";

const notificationsCreated = new Counter("k6_soak_notifications_created");
const notificationErrors = new Rate("k6_soak_notification_errors");
const outboxPending = new Gauge("k6_outbox_pending_count");
const retryScheduled = new Gauge("k6_deliveries_retry_scheduled_count");
const deadLettered = new Gauge("k6_deliveries_dead_lettered_count");

export const options = {
  scenarios: {
    soak: {
      executor: "constant-vus",
      vus: Number(__ENV.VUS || 100),
      duration: __ENV.DURATION || "30m",
      gracefulStop: "1m",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.03"],
    http_req_duration: ["p(95)<1000", "p(99)<2500"],
    k6_soak_notification_errors: ["rate<0.03"],
  },
};

export function setup() {
  if (PRODUCT_ID) {
    return { productId: PRODUCT_ID, templateKey: TEMPLATE_KEY };
  }

  return createProductAndTemplate("soak");
}

export default function (data) {
  const response = postJson("/api/v1/notifications", notificationPayload(data, "soak"));
  const ok = response.status === 201;

  notificationErrors.add(!ok);
  if (ok) {
    notificationsCreated.add(1);
  }

  check(response, {
    "notification accepted during soak": (res) => res.status === 201,
  });

  if (__ITER % Number(__ENV.METRIC_SAMPLE_EVERY || 50) === 0) {
    captureBackendGauge("outbox_pending_count", outboxPending);
    captureBackendGauge("deliveries_retry_scheduled_count", retryScheduled);
    captureBackendGauge("deliveries_dead_lettered_count", deadLettered);
  }

  sleep(Number(__ENV.SLEEP_SECONDS || 0.2));
}

function createProductAndTemplate(label) {
  const suffix = unique(label);
  const product = postJson("/api/v1/admin/products", {
    name: `Load ${label} ${suffix}`,
  });

  check(product, { "product created": (res) => res.status === 201 });

  const productId = product.json("id");
  const templateKey = `${TEMPLATE_KEY}-${suffix}`;
  const template = postJson("/api/v1/admin/templates", {
    productId,
    templateKey,
    channel: "EMAIL",
    version: 1,
    subject: "Load test soak",
    content: "Hello {{name}}, this soak notification was generated by k6.",
    status: "ACTIVE",
  });

  check(template, { "template created": (res) => res.status === 201 });
  return { productId, templateKey };
}

function notificationPayload(data, prefix) {
  const id = unique(prefix);

  return {
    productId: data.productId,
    templateKey: data.templateKey,
    requestedChannels: ["EMAIL"],
    externalUserId: `soak-user-${id}`,
    idempotencyKey: `soak-${id}`,
    category: "LOAD_TEST",
    priority: "NORMAL",
    payload: {
      name: "Soak Tester",
      runId: id,
    },
    recipient: {
      email: `soak-${id}@example.test`,
    },
  };
}

function captureBackendGauge(metricName, gauge) {
  const response = http.get(`${BASE_URL}/actuator/prometheus`, { timeout: "10s" });
  if (response.status !== 200) {
    return;
  }

  const regex = new RegExp(`^${metricName}(?:\\{[^}]*\\})?\\s+([0-9.eE+-]+)$`, "m");
  const match = response.body.match(regex);
  if (match) {
    gauge.add(Number(match[1]));
  }
}

function postJson(path, body) {
  return http.post(`${BASE_URL}${path}`, JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    timeout: "30s",
  });
}

function unique(prefix) {
  const vu = typeof __VU === "undefined" ? 0 : __VU;
  const iter = typeof __ITER === "undefined" ? 0 : __ITER;
  return `${prefix}-${Date.now()}-${vu}-${iter}-${Math.random().toString(36).slice(2, 10)}`;
}
