import http from "k6/http";
import encoding from "k6/encoding";
import { check, sleep } from "k6";
import { Counter, Gauge, Rate } from "k6/metrics";

const BASE_URL = __ENV.BASE_URL || "http://localhost:8080";
const PRODUCT_ID = __ENV.PRODUCT_ID;
const TEMPLATE_KEY = __ENV.TEMPLATE_KEY || "load-test-email";
const RABBITMQ_API = __ENV.RABBITMQ_API || "http://localhost:15672";
const RABBITMQ_USER = __ENV.RABBITMQ_USER || "notification";
const RABBITMQ_PASSWORD = __ENV.RABBITMQ_PASSWORD || "notification";
const RABBITMQ_AUTH = `Basic ${encoding.b64encode(`${RABBITMQ_USER}:${RABBITMQ_PASSWORD}`)}`;
const RABBITMQ_VHOST = encodeURIComponent(__ENV.RABBITMQ_VHOST || "/");
const QUEUES = (__ENV.RABBITMQ_QUEUES || "notifications.high.email,notifications.normal.email,notifications.low.email")
  .split(",")
  .map((queue) => queue.trim())
  .filter(Boolean);

const notificationErrors = new Rate("k6_spike_notification_errors");
const notificationsCreated = new Counter("k6_spike_notifications_created");
const rabbitBacklog = new Gauge("k6_rabbitmq_backlog_messages");
const outboxPending = new Gauge("k6_outbox_pending_count");

export const options = {
  scenarios: {
    spike: {
      executor: "ramping-vus",
      stages: [
        { duration: __ENV.WARMUP_DURATION || "30s", target: Number(__ENV.WARMUP_VUS || 10) },
        { duration: __ENV.SPIKE_RAMP_DURATION || "30s", target: Number(__ENV.SPIKE_VUS || 1000) },
        { duration: __ENV.SPIKE_HOLD_DURATION || "2m", target: Number(__ENV.SPIKE_VUS || 1000) },
        { duration: __ENV.RECOVERY_DURATION || "2m", target: Number(__ENV.WARMUP_VUS || 10) },
        { duration: "30s", target: 0 },
      ],
      gracefulRampDown: "30s",
    },
  },
  thresholds: {
    http_req_failed: ["rate<0.15"],
    http_req_duration: ["p(95)<3000", "p(99)<6000"],
    k6_spike_notification_errors: ["rate<0.15"],
  },
};

export function setup() {
  if (PRODUCT_ID) {
    return { productId: PRODUCT_ID, templateKey: TEMPLATE_KEY };
  }

  return createProductAndTemplate("spike");
}

export default function (data) {
  const response = postJson("/api/v1/notifications", notificationPayload(data, "spike"));
  const ok = response.status === 201;

  notificationErrors.add(!ok);
  if (ok) {
    notificationsCreated.add(1);
  }

  check(response, {
    "notification accepted during spike": (res) => res.status === 201,
    "spike latency below 3s": (res) => res.timings.duration < 3000,
  });

  if (__ITER % Number(__ENV.METRIC_SAMPLE_EVERY || 25) === 0) {
    captureBacklog();
    captureOutboxPending();
  }

  sleep(Number(__ENV.SLEEP_SECONDS || 0.05));
}

function createProductAndTemplate(label) {
  const suffix = unique(label);
  const product = postJson("/api/v1/admin/products", {
    name: `Load ${label} ${suffix}`,
  });

  check(product, { "product created": (res) => res.status === 201 });

  const productId = product.json("id");
  const templateKey = `${TEMPLATE_KEY}-${suffix}`;
  const template = postJson("/api/v1/admin/templates", {
    productId,
    templateKey,
    channel: "EMAIL",
    version: 1,
    subject: "Load test spike",
    content: "Hello {{name}}, this spike item was generated by k6.",
    status: "ACTIVE",
  });

  check(template, { "template created": (res) => res.status === 201 });
  return { productId, templateKey };
}

function notificationPayload(data, prefix) {
  const id = unique(prefix);

  return {
    productId: data.productId,
    templateKey: data.templateKey,
    requestedChannels: ["EMAIL"],
    externalUserId: `spike-user-${id}`,
    idempotencyKey: `spike-${id}`,
    category: "LOAD_TEST",
    priority: pickPriority(),
    payload: {
      name: "Spike Tester",
      runId: id,
    },
    recipient: {
      email: `spike-${id}@example.test`,
    },
  };
}

function captureBacklog() {
  for (const queue of QUEUES) {
    const response = http.get(`${RABBITMQ_API}/api/queues/${RABBITMQ_VHOST}/${encodeURIComponent(queue)}`, {
      headers: { Authorization: RABBITMQ_AUTH },
      timeout: "10s",
    });

    if (response.status === 200) {
      rabbitBacklog.add(Number(response.json("messages") || 0), { queue });
    }
  }
}

function captureOutboxPending() {
  const response = http.get(`${BASE_URL}/actuator/prometheus`, { timeout: "10s" });
  if (response.status !== 200) {
    return;
  }

  const match = response.body.match(/^outbox_pending_count(?:\{[^}]*\})?\s+([0-9.eE+-]+)$/m);
  if (match) {
    outboxPending.add(Number(match[1]));
  }
}

function pickPriority() {
  const value = Math.random();
  if (value < 0.2) {
    return "HIGH";
  }
  if (value < 0.9) {
    return "NORMAL";
  }
  return "LOW";
}

function postJson(path, body) {
  return http.post(`${BASE_URL}${path}`, JSON.stringify(body), {
    headers: { "Content-Type": "application/json" },
    timeout: "30s",
  });
}

function unique(prefix) {
  const vu = typeof __VU === "undefined" ? 0 : __VU;
  const iter = typeof __ITER === "undefined" ? 0 : __ITER;
  return `${prefix}-${Date.now()}-${vu}-${iter}-${Math.random().toString(36).slice(2, 10)}`;
}
